DO $$
DECLARE
  v_user_id uuid := COALESCE((SELECT user_id FROM public.wine_countries LIMIT 1), (SELECT id FROM auth.users LIMIT 1));
  r record;
  v_country_id uuid;
  v_region_id uuid;
  v_sub_id uuid;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'No user available'; END IF;
  FOR r IN SELECT * FROM (VALUES
    ('Europe','Germany','Mosel','Mittelmosel','Pradikatswein','Mosel'),
    ('Europe','Germany','Mosel','Saar','Pradikatswein','Mosel'),
    ('Europe','Germany','Mosel','Ruwer','Pradikatswein','Mosel'),
    ('Europe','Germany','Mosel','Terrassenmosel','Pradikatswein','Mosel'),
    ('Europe','Germany','Rheingau','Rheingau','Pradikatswein','Rheingau'),
    ('Europe','Germany','Rheinhessen','Rheinhessen','Pradikatswein','Rheinhessen'),
    ('Europe','Germany','Pfalz','Pfalz','Pradikatswein','Pfalz'),
    ('Europe','Germany','Nahe','Nahe','Pradikatswein','Nahe'),
    ('Europe','Germany','Franken','Franken','Pradikatswein','Franken'),
    ('Europe','Germany','Baden','Kaiserstuhl','Pradikatswein','Baden'),
    ('Europe','Germany','Baden','Markgraflerland','Pradikatswein','Baden'),
    ('Europe','Germany','Baden','Ortenau','Pradikatswein','Baden'),
    ('Europe','Germany','Baden','Breisgau','Pradikatswein','Baden'),
    ('Europe','Germany','Württemberg','Württemberg','Pradikatswein','Württemberg'),
    ('Europe','Germany','Mittelrhein','Mittelrhein','Pradikatswein','Mittelrhein'),
    ('Europe','Germany','Ahr','Ahr','Pradikatswein','Ahr'),
    ('Europe','Germany','Saale-Unstrut','Saale-Unstrut','Pradikatswein','Saale-Unstrut'),
    ('Europe','Germany','Sachsen','Sachsen','Pradikatswein','Sachsen'),
    ('Europe','Germany','Hessische Bergstrasse','Hessische Bergstrasse','Pradikatswein','Hessische Bergstrasse'),
    ('Europe','Austria','Niederösterreich','Wachau','Qualitätswein','Wachau'),
    ('Europe','Austria','Niederösterreich','Kremstal','DAC','Kremstal'),
    ('Europe','Austria','Niederösterreich','Kamptal','DAC','Kamptal'),
    ('Europe','Austria','Niederösterreich','Traisental','DAC','Traisental'),
    ('Europe','Austria','Niederösterreich','Wagram','DAC','Wagram'),
    ('Europe','Austria','Niederösterreich','Weinviertel','DAC','Weinviertel'),
    ('Europe','Austria','Niederösterreich','Carnuntum','DAC','Carnuntum'),
    ('Europe','Austria','Niederösterreich','Thermenregion','Qualitätswein','Thermenregion'),
    ('Europe','Austria','Wien','Wien','DAC','Wien'),
    ('Europe','Austria','Burgenland','Neusiedlersee','DAC','Neusiedlersee'),
    ('Europe','Austria','Burgenland','Leithaberg','DAC','Leithaberg'),
    ('Europe','Austria','Burgenland','Eisenberg','DAC','Eisenberg'),
    ('Europe','Austria','Burgenland','Rosalia','DAC','Rosalia'),
    ('Europe','Austria','Burgenland','Rust','Pradikat','Rust Ausbruch'),
    ('Europe','Austria','Steiermark','Südsteiermark','DAC','Südsteiermark'),
    ('Europe','Austria','Steiermark','Weststeiermark','DAC','Weststeiermark'),
    ('Europe','Austria','Steiermark','Vulkanland Steiermark','DAC','Vulkanland Steiermark'),
    ('Europe','Switzerland','Valais','Sion & Zentralwallis','AOC Valais','Valais'),
    ('Europe','Switzerland','Valais','Leytron / Chamoson / Fully','AOC Valais','Valais'),
    ('Europe','Switzerland','Valais','Visperterminen','AOC Valais','Valais'),
    ('Europe','Switzerland','Vaud','La Cote','AOC Vaud','La Cote'),
    ('Europe','Switzerland','Vaud','Lavaux','AOC Vaud','Lavaux'),
    ('Europe','Switzerland','Vaud','Lavaux','AOC Vaud','Dezaley'),
    ('Europe','Switzerland','Vaud','Lavaux','AOC Vaud','Calamin'),
    ('Europe','Switzerland','Vaud','Chablais','AOC Vaud','Chablais'),
    ('Europe','Switzerland','Vaud','Cotes de l’Orbe','AOC Vaud','Cotes de l’Orbe'),
    ('Europe','Switzerland','Vaud','Bonvillars','AOC Vaud','Bonvillars'),
    ('Europe','Switzerland','Vaud','Vully (vaudois)','AOC Vaud','Vully'),
    ('Europe','Switzerland','Geneve','Mandement','AOC Geneve','Geneve'),
    ('Europe','Switzerland','Geneve','Arve-et-Lac','AOC Geneve','Geneve'),
    ('Europe','Switzerland','Geneve','Arve-et-Rhone','AOC Geneve','Geneve'),
    ('Europe','Switzerland','Neuchatel','Neuchatel','AOC Neuchatel','Neuchatel'),
    ('Europe','Switzerland','Fribourg','Vully (fribourgeois)','AOC Fribourg','Vully'),
    ('Europe','Switzerland','Schaffhausen','Hallau / Osterfingen','AOC Schaffhausen','Schaffhausen'),
    ('Europe','Switzerland','Thurgau','Thurgau','AOC Thurgau','Thurgau'),
    ('Europe','Switzerland','Zurich','Zurichsee / Weinland','AOC Zurich','Zurich'),
    ('Europe','Switzerland','Aargau','Aargau','AOC Aargau','Aargau'),
    ('Europe','Switzerland','Graubünden','Bündner Herrschaft','AOC Graubünden','Bündner Herrschaft'),
    ('Europe','Switzerland','Ticino','Sottoceneri / Sopraceneri','DOC Ticino','Ticino'),
    ('Europe','Greece','Makedonia','Naoussa','PDO','Naoussa'),
    ('Europe','Greece','Makedonia','Amyndeon','PDO','Amyndeon'),
    ('Europe','Greece','Makedonia','Goumenissa','PDO','Goumenissa'),
    ('Europe','Greece','Makedonia','Halkidiki','PDO','Cotes de Meliton'),
    ('Europe','Greece','Ipeiros','Ioannina','PDO','Zitsa'),
    ('Europe','Greece','Thessalia','Larissa','PDO','Rapsani'),
    ('Europe','Greece','Thessalia','Volos','PDO','Anchialos'),
    ('Europe','Greece','Attiki','Attiki','PDO','Savatiano'),
    ('Europe','Greece','Peloponnisos','Korinthia','PDO','Nemea'),
    ('Europe','Greece','Peloponnisos','Arkadia','PDO','Mantinia'),
    ('Europe','Greece','Peloponnisos','Achaia','PDO','Patras'),
    ('Europe','Greece','Peloponnisos','Achaia','PDO','Mavrodaphne of Patras'),
    ('Europe','Greece','Nisia Aigaiou','Santorini','PDO','Santorini'),
    ('Europe','Greece','Nisia Aigaiou','Limnos','PDO','Muscat of Limnos'),
    ('Europe','Greece','Nisia Aigaiou','Rodos','PDO','Rodos'),
    ('Europe','Greece','Nisia Aigaiou','Samos','PDO','Muscat of Samos'),
    ('Europe','Greece','Ionia Nisia','Kefalonia','PDO','Robola of Cephalonia'),
    ('Europe','Greece','Ionia Nisia','Kefalonia','PDO','Mavrodaphne of Cephalonia'),
    ('Europe','Greece','Ionia Nisia','Lefkada','PDO','Lefkada'),
    ('Europe','Greece','Kriti','Iraklio','PDO','Archanes'),
    ('Europe','Greece','Kriti','Iraklio','PDO','Peza'),
    ('Europe','Greece','Kriti','Iraklio','PDO','Dafnes'),
    ('Europe','Greece','Kriti','Lasithi','PDO','Sitia'),
    ('Europe','Georgia','Kakheti','Alazani Valley','PDO','Tsinandali'),
    ('Europe','Georgia','Kakheti','Alazani Valley','PDO','Mukuzani'),
    ('Europe','Georgia','Kakheti','Alazani Valley','PDO','Kindzmarauli'),
    ('Europe','Georgia','Kakheti','Alazani Valley','PDO','Akhasheni'),
    ('Europe','Georgia','Kakheti','Alazani Valley','PDO','Gurjaani'),
    ('Europe','Georgia','Racha-Lechkhumi','Racha','PDO','Khvanchkara'),
    ('Europe','Georgia','Imereti','Imereti','PGI','Imereti'),
    ('Europe','Georgia','Kartli','Kartli','PGI','Kartli'),
    ('Europe','Georgia','Adjara','Adjara','PGI','Adjara'),
    ('Europe','Hungary','Tokaj-Hegyalja','Tokaj','OEM','Tokaj'),
    ('Europe','Hungary','Eger','Eger','OEM','Egri Bikaver'),
    ('Europe','Hungary','Villany','Villany','OEM','Villany'),
    ('Europe','Hungary','Szekszard','Szekszard','OEM','Szekszard'),
    ('Europe','Hungary','Somlo','Somlo','OEM','Somlo'),
    ('Europe','Hungary','Badacsony','Badacsony','OEM','Badacsony'),
    ('Europe','Hungary','Balatonfured-Csopak','Balatonfured-Csopak','OEM','Balatonfured-Csopak'),
    ('Europe','Hungary','Matra','Matra','OEM','Matra'),
    ('Europe','Hungary','Etyek-Buda','Etyek-Buda','OEM','Etyek-Buda'),
    ('Europe','Czech Republic','Morava','Znojemska','CHOP','Znojemska'),
    ('Europe','Czech Republic','Morava','Mikulovska','CHOP','Mikulovska'),
    ('Europe','Czech Republic','Morava','Velkopavlovicka','CHOP','Velkopavlovicka'),
    ('Europe','Czech Republic','Morava','Slovacka','CHOP','Slovacka'),
    ('Europe','Czech Republic','Cechy','Melnická','CHOP','Melnická'),
    ('Europe','Czech Republic','Cechy','Litomericka','CHOP','Litomericka'),
    ('Europe','Slovakia','Malokarpatska','Male Karpaty','CHOP','Malokarpatska'),
    ('Europe','Slovakia','Juzno-slovenská','Southern Slovakia','CHOP','Juzno-slovenská'),
    ('Europe','Slovakia','Nitrianska','Nitra','CHOP','Nitrianska'),
    ('Europe','Slovakia','Tokajská','Slovak Tokaj','CHOP','Tokajská'),
    ('Europe','Slovakia','Stredoslovenská','Central Slovakia','CHOP','Stredoslovenská'),
    ('Europe','Slovakia','Východoslovenská','Eastern Slovakia','CHOP','Východoslovenská'),
    ('Europe','Slovenia','Primorska','Goriska Brda','ZGP','Goriska Brda'),
    ('Europe','Slovenia','Primorska','Kras','ZGP','Kras'),
    ('Europe','Slovenia','Primorska','Koper','ZGP','Koper'),
    ('Europe','Slovenia','Primorska','Vipavska dolina','ZGP','Vipavska dolina'),
    ('Europe','Slovenia','Podravje','Stajerska Slovenija','ZGP','Stajerska Slovenija'),
    ('Europe','Slovenia','Podravje','Prekmurje','ZGP','Prekmurje'),
    ('Europe','Slovenia','Posavje','Bela Krajina','ZGP','Bela Krajina'),
    ('Europe','Slovenia','Posavje','Bizeljsko-Sremic','ZGP','Bizeljsko-Sremic'),
    ('Europe','Slovenia','Posavje','Dolenjska','ZGP','Dolenjska'),
    ('Europe','Romania','Moldova','Cotnari','DOC','Cotnari'),
    ('Europe','Romania','Moldova','Iasi','DOC','Iasi'),
    ('Europe','Romania','Moldova','Husi','DOC','Husi'),
    ('Europe','Romania','Muntenia & Oltenia','Dealu Mare','DOC','Dealu Mare'),
    ('Europe','Romania','Muntenia & Oltenia','Dragasani','DOC','Dragasani'),
    ('Europe','Romania','Dobrogea','Murfatlar','DOC','Murfatlar'),
    ('Europe','Romania','Transylvania','Tarnave','DOC','Tarnave'),
    ('Europe','Romania','Transylvania','Alba Iulia-Aiud','DOC','Alba Iulia-Aiud'),
    ('Europe','Romania','Banat','Recas','DOC','Recas'),
    ('Europe','Romania','Crisana & Maramures','Mini-Maderat','DOC','Mini-Maderat'),
    ('Europe','Bulgaria','Dunav Plain','Svishtov / Pleven','DGO','Danube Plain'),
    ('Europe','Bulgaria','Thracian Valley','Plovdiv / Stara Zagora','DGO','Thracian Valley'),
    ('Europe','Bulgaria','Rose Valley','Sungurlare / Sliven','DGO','Rose Valley'),
    ('Europe','Bulgaria','Black Sea','Shumen / Varna / Burgas','DGO','Black Sea'),
    ('Europe','Bulgaria','Struma Valley','Melnik','DGO','Struma Valley'),
    ('Europe','Croatia','Primorska','Istra','KPN','Istra'),
    ('Europe','Croatia','Primorska','Kvarner','KPN','Kvarner'),
    ('Europe','Croatia','Primorska','Sjeverna Dalmacija','KPN','Sjeverna Dalmacija'),
    ('Europe','Croatia','Primorska','Srednja i Juzna Dalmacija','KPN','Dingac'),
    ('Europe','Croatia','Primorska','Srednja i Juzna Dalmacija','KPN','Postup'),
    ('Europe','Croatia','Kontinentalna','Slavonija','KPN','Slavonija'),
    ('Europe','Croatia','Kontinentalna','Podunavlje','KPN','Podunavlje'),
    ('Europe','Croatia','Kontinentalna','Plesivica','KPN','Plesivica'),
    ('Europe','Serbia','Fruska Gora','Fruska Gora','KGP','Fruska Gora'),
    ('Europe','Serbia','Zupa','Zupa Aleksandrovacka','KGP','Zupa'),
    ('Europe','Serbia','Timok','Timoska krajina','KGP','Timok'),
    ('Europe','Moldova','Codru','Codru','DOC','Codru'),
    ('Europe','Moldova','Valul lui Traian','Valul lui Traian','DOC','Valul lui Traian'),
    ('Europe','Moldova','Stefan Voda','Stefan Voda','DOC','Stefan Voda'),
    ('Europe','Moldova','Balti','Balti','DOC','Balti'),
    ('Europe','Ukraine','Crimea','Southern Coast','PDO','Yuzhnyi Bereg'),
    ('Europe','Ukraine','Crimea','Sevastopol','PDO','Sevastopol'),
    ('Europe','Ukraine','Odessa','Shabo','PDO','Shabo'),
    ('Europe','Ukraine','Zakarpattia','Zakarpattia','PGI','Zakarpattia'),
    ('Europe','Luxembourg','Moselle Luxembourgeoise','Moselle','AOP','Moselle Luxembourgeoise'),
    ('Europe','England & Wales','Sussex','West & East Sussex','PDO','Sussex'),
    ('Europe','England & Wales','Kent','Kent','PGI','English Wine'),
    ('Europe','England & Wales','Hampshire','Hampshire','PGI','English Wine'),
    ('Europe','England & Wales','East Anglia','Essex / Suffolk / Norfolk','PGI','English Wine'),
    ('Europe','England & Wales','Wales','Wales','PDO','Welsh Wine'),
    ('Europe','England & Wales','South-West','Cornwall & Devon','PGI','English Wine'),
    ('Europe','Belgium','Hageland','Flemish Brabant','AOP','Hageland'),
    ('Europe','Belgium','Haspengouw','Limburg & Brabant','AOP','Haspengouw'),
    ('Europe','Belgium','Coteaux de Sambre-et-Meuse','Namur & Liege','AOP','Coteaux de Sambre-et-Meuse'),
    ('Europe','Netherlands','Zuid-Limburg','Maas Valley','BGA','Zuid-Limburg'),
    ('Oceania','Australia','South Australia','Barossa Valley','GI','Barossa Valley'),
    ('Oceania','Australia','South Australia','Eden Valley','GI','Eden Valley'),
    ('Oceania','Australia','South Australia','McLaren Vale','GI','McLaren Vale'),
    ('Oceania','Australia','South Australia','Currency Creek','GI','Currency Creek'),
    ('Oceania','Australia','South Australia','Langhorne Creek','GI','Langhorne Creek'),
    ('Oceania','Australia','South Australia','Kangaroo Island','GI','Kangaroo Island'),
    ('Oceania','Australia','South Australia','Adelaide Hills','GI','Adelaide Hills'),
    ('Oceania','Australia','South Australia','Clare Valley','GI','Clare Valley'),
    ('Oceania','Australia','South Australia','Coonawarra','GI','Coonawarra'),
    ('Oceania','Australia','South Australia','Padthaway','GI','Padthaway'),
    ('Oceania','Australia','South Australia','Wrattonbully','GI','Wrattonbully'),
    ('Oceania','Australia','South Australia','Robe','GI','Robe'),
    ('Oceania','Australia','South Australia','Mount Benson','GI','Mount Benson'),
    ('Oceania','Australia','South Australia','Mount Gambier','GI','Mount Gambier'),
    ('Oceania','Australia','Victoria','Yarra Valley','GI','Yarra Valley'),
    ('Oceania','Australia','Victoria','Mornington Peninsula','GI','Mornington Peninsula'),
    ('Oceania','Australia','Victoria','Macedon Ranges','GI','Macedon Ranges'),
    ('Oceania','Australia','Victoria','Heathcote','GI','Heathcote'),
    ('Oceania','Australia','Victoria','Grampians','GI','Grampians'),
    ('Oceania','Australia','Victoria','Pyrenees','GI','Pyrenees'),
    ('Oceania','Australia','Victoria','Beechworth','GI','Beechworth'),
    ('Oceania','Australia','Victoria','Rutherglen','GI','Rutherglen'),
    ('Oceania','Australia','Victoria','Goulburn Valley','GI','Goulburn Valley'),
    ('Oceania','Australia','Victoria','King Valley','GI','King Valley'),
    ('Oceania','Australia','Western Australia','Margaret River','GI','Margaret River'),
    ('Oceania','Australia','Western Australia','Great Southern','GI','Great Southern'),
    ('Oceania','Australia','Western Australia','Great Southern','GI','Albany'),
    ('Oceania','Australia','Western Australia','Great Southern','GI','Denmark'),
    ('Oceania','Australia','Western Australia','Great Southern','GI','Frankland River'),
    ('Oceania','Australia','Western Australia','Great Southern','GI','Mount Barker'),
    ('Oceania','Australia','Western Australia','Great Southern','GI','Porongurup'),
    ('Oceania','Australia','Western Australia','Pemberton','GI','Pemberton'),
    ('Oceania','Australia','Western Australia','Manjimup','GI','Manjimup'),
    ('Oceania','Australia','Western Australia','Swan District','GI','Swan District'),
    ('Oceania','Australia','Western Australia','Perth Hills','GI','Perth Hills'),
    ('Oceania','Australia','New South Wales','Hunter Valley','GI','Hunter Valley'),
    ('Oceania','Australia','New South Wales','Mudgee','GI','Mudgee'),
    ('Oceania','Australia','New South Wales','Orange','GI','Orange'),
    ('Oceania','Australia','New South Wales','Hilltops','GI','Hilltops'),
    ('Oceania','Australia','New South Wales','Canberra District','GI','Canberra District'),
    ('Oceania','Australia','New South Wales','Riverina','GI','Riverina'),
    ('Oceania','Australia','Tasmania','Tamar Valley','GI','Tamar Valley'),
    ('Oceania','Australia','Tasmania','Coal River Valley','GI','Coal River Valley'),
    ('Oceania','Australia','Tasmania','East Coast','GI','East Coast Tasmania'),
    ('Oceania','Australia','Queensland','Granite Belt','GI','Granite Belt'),
    ('Oceania','Australia','Queensland','South Burnett','GI','South Burnett'),
    ('Oceania','New Zealand','Marlborough','Wairau Valley','GI','Marlborough'),
    ('Oceania','New Zealand','Marlborough','Awatere Valley','GI','Marlborough'),
    ('Oceania','New Zealand','Marlborough','Southern Valleys','GI','Marlborough'),
    ('Oceania','New Zealand','Hawke’s Bay','Gimblett Gravels','GI','Hawke’s Bay'),
    ('Oceania','New Zealand','Hawke’s Bay','Bridge Pa Triangle','GI','Hawke’s Bay'),
    ('Oceania','New Zealand','Central Otago','Bannockburn','GI','Central Otago'),
    ('Oceania','New Zealand','Central Otago','Cromwell Basin','GI','Central Otago'),
    ('Oceania','New Zealand','Central Otago','Gibbston','GI','Central Otago'),
    ('Oceania','New Zealand','Central Otago','Wanaka','GI','Central Otago'),
    ('Oceania','New Zealand','Central Otago','Bendigo','GI','Central Otago'),
    ('Oceania','New Zealand','Central Otago','Alexandra','GI','Central Otago'),
    ('Oceania','New Zealand','Canterbury','Waipara Valley','GI','Canterbury'),
    ('Oceania','New Zealand','Canterbury','Christchurch Plains','GI','Canterbury'),
    ('Oceania','New Zealand','Wairarapa','Martinborough','GI','Martinborough'),
    ('Oceania','New Zealand','Nelson','Waimea Plains','GI','Nelson'),
    ('Oceania','New Zealand','Nelson','Moutere Hills','GI','Nelson'),
    ('Oceania','New Zealand','Waitaki Valley','Waitaki Valley','GI','Waitaki Valley'),
    ('Oceania','New Zealand','Gisborne','Gisborne','GI','Gisborne'),
    ('Oceania','New Zealand','Auckland','Waiheke Island','GI','Auckland'),
    ('Oceania','New Zealand','Auckland','Henderson','GI','Auckland'),
    ('Oceania','New Zealand','Auckland','Matakana','GI','Auckland'),
    ('Oceania','New Zealand','Northland','Northland','GI','Northland'),
    ('Africa','South Africa','Western Cape','Stellenbosch','WO District','Stellenbosch'),
    ('Africa','South Africa','Western Cape','Franschhoek','WO Ward','Franschhoek'),
    ('Africa','South Africa','Western Cape','Paarl','WO District','Paarl'),
    ('Africa','South Africa','Western Cape','Swartland','WO District','Swartland'),
    ('Africa','South Africa','Western Cape','Constantia','WO Ward','Constantia'),
    ('Africa','South Africa','Western Cape','Elgin','WO Ward','Elgin'),
    ('Africa','South Africa','Western Cape','Walker Bay','WO District','Walker Bay'),
    ('Africa','South Africa','Western Cape','Walker Bay','WO Ward','Hemel-en-Aarde Valley'),
    ('Africa','South Africa','Western Cape','Overberg','WO District','Overberg'),
    ('Africa','South Africa','Western Cape','Overberg','WO Ward','Elim'),
    ('Africa','South Africa','Western Cape','Robertson','WO District','Robertson'),
    ('Africa','South Africa','Western Cape','Worcester','WO District','Worcester'),
    ('Africa','South Africa','Western Cape','Breedekloof','WO District','Breedekloof'),
    ('Africa','South Africa','Northern Cape','Orange River','WO Region','Orange River'),
    ('Africa','South Africa','KwaZulu-Natal','KwaZulu-Natal','WO Geographical Unit','KwaZulu-Natal'),
    ('Africa','Morocco','Meknes-Fes','Meknes','AOG','Guerrouane'),
    ('Africa','Morocco','Meknes-Fes','Meknes','AOG','Beni M’Tir'),
    ('Africa','Morocco','Meknes-Fes','Meknes','AOG','Zerhoune'),
    ('Africa','Morocco','Meknes-Fes','Meknes','AOG','Sais'),
    ('Africa','Morocco','Rabat-Casablanca','Gharb / Chaouia','AOG','Zenata'),
    ('Africa','Morocco','Oriental','Berkane / Angad','AOG','Angad'),
    ('Africa','Algeria','Mascara','Mascara','AOIG','Coteaux de Mascara'),
    ('Africa','Algeria','Tlemcen','Tlemcen','AOIG','Coteaux de Tlemcen'),
    ('Africa','Algeria','Medea','Ain Bessem','AOIG','Ain Bessem-Bouira'),
    ('Africa','Algeria','Miliana','Miliana','AOIG','Coteaux du Zaccar'),
    ('Africa','Tunisia','Cap Bon','Kelibia / Grombalia','AOC','Kelibia'),
    ('Africa','Tunisia','Tunis','Mornag','AOC','Mornag'),
    ('Africa','Tunisia','Medjerda Valley','Tebourba','AOC','Coteaux de Tebourba'),
    ('Africa','Ethiopia','Rift Valley','Ziway',NULL,'Ziway'),
    ('Africa','Kenya','Rift Valley','Naivasha',NULL,'Lake Naivasha'),
    ('Asia','China','Xinjiang','Turpan / Yili / Yanqi',NULL,'Xinjiang'),
    ('Asia','China','Ningxia','Helan Mountain East','GI','Helan Mountain East Foothills'),
    ('Asia','China','Shandong','Penglai / Yantai',NULL,'Penglai'),
    ('Asia','China','Shandong','Changli',NULL,'Changli'),
    ('Asia','China','Hebei','Huailai / Changli',NULL,'Huailai'),
    ('Asia','China','Yunnan','Shangri-La (Deqin)',NULL,'Shangri-La'),
    ('Asia','China','Yunnan','Mile',NULL,'Mile'),
    ('Asia','China','Gansu','Hexi Corridor',NULL,'Hexi Corridor'),
    ('Asia','China','Shanxi','Taiyuan',NULL,'Shanxi'),
    ('Asia','Japan','Yamanashi','Katsunuma / Isawa','GI','Yamanashi'),
    ('Asia','Japan','Nagano','Chikumagawa / Obuse','GI','Nagano'),
    ('Asia','Japan','Hokkaido','Yoichi / Furano','GI','Hokkaido'),
    ('Asia','Japan','Yamagata','Takahata / Sagae','GI','Yamagata'),
    ('Asia','Japan','Osaka','Ikeda','GI','Osaka'),
    ('Asia','India','Maharashtra','Nashik','State GI','Nashik'),
    ('Asia','India','Maharashtra','Sangli / Baramati','State GI','Sangli'),
    ('Asia','India','Karnataka','Nandi Hills','State GI','Nandi Hills'),
    ('Asia','India','Himachal Pradesh','Kullu Valley',NULL,'Kullu'),
    ('Asia','Lebanon','Bekaa Valley','Zahle / Baalbek',NULL,'Bekaa'),
    ('Asia','Lebanon','Mont-Liban','Kesrouane / Batroun',NULL,'Mont-Liban'),
    ('Asia','Israel','Galil','Upper Galilee / Golan Heights',NULL,'Galil'),
    ('Asia','Israel','Shomron','Carmel slopes',NULL,'Shomron'),
    ('Asia','Israel','Shimshon','Judean foothills',NULL,'Shimshon'),
    ('Asia','Israel','Negev','Ramat Arad / Mitzpe Ramon',NULL,'Negev'),
    ('Asia','Israel','Judean Hills','Jerusalem mountains',NULL,'Judean Hills'),
    ('Asia','Turkey','Trakya & Marmara','Tekirdag / Bozcaada',NULL,'Trakya'),
    ('Asia','Turkey','Ege','Izmir / Manisa / Denizli',NULL,'Ege'),
    ('Asia','Turkey','Ic Anadolu','Cappadocia',NULL,'Cappadocia'),
    ('Asia','Turkey','Dogu Anadolu','Elazig / Diyarbakir',NULL,'Elazig'),
    ('Asia','Turkey','Güneydogu Anadolu','Gaziantep / Maras',NULL,'Güneydogu Anadolu'),
    ('Asia','Armenia','Ararat Valley','Yerevan / Artashat','PDO','Ararat'),
    ('Asia','Armenia','Vayots Dzor','Areni','PDO','Areni'),
    ('Asia','Armenia','Tavush','Dilijan / Ijevan','PGI','Tavush'),
    ('Asia','Armenia','Aragatsotn','Talish / Oshakan','PGI','Aragatsotn'),
    ('Asia','Azerbaijan','Ganja-Gazakh','Shamkhor / Tovuz',NULL,'Ganja-Gazakh'),
    ('Asia','Azerbaijan','Shirvan','Shamakhy / Goychay',NULL,'Shirvan'),
    ('Asia','Thailand','Nakhon Ratchasima','Khao Yai',NULL,'Khao Yai'),
    ('Asia','Thailand','Prachuap Khiri Khan','Hua Hin Hills',NULL,'Hua Hin Hills'),
    ('Asia','Myanmar','Shan State','Inle Lake / Taunggyi',NULL,'Aythaya')
  ) AS t(continent, country, region, sub_region, atype, aname)
  LOOP
    SELECT id INTO v_country_id FROM public.wine_countries WHERE user_id = v_user_id AND name = r.country LIMIT 1;
    IF v_country_id IS NULL THEN
      INSERT INTO public.wine_countries(user_id,name,continent,sort_order)
      VALUES (v_user_id, r.country, r.continent, (SELECT COALESCE(MAX(sort_order),0)+1 FROM public.wine_countries WHERE user_id=v_user_id))
      RETURNING id INTO v_country_id;
    ELSE
      UPDATE public.wine_countries SET continent = COALESCE(continent, r.continent) WHERE id = v_country_id;
    END IF;

    SELECT id INTO v_region_id FROM public.wine_regions WHERE user_id = v_user_id AND country_id = v_country_id AND name = r.region LIMIT 1;
    IF v_region_id IS NULL THEN
      INSERT INTO public.wine_regions(user_id,country_id,name,sort_order)
      VALUES (v_user_id, v_country_id, r.region, (SELECT COALESCE(MAX(sort_order),0)+1 FROM public.wine_regions WHERE user_id=v_user_id AND country_id=v_country_id))
      RETURNING id INTO v_region_id;
    END IF;

    SELECT id INTO v_sub_id FROM public.wine_sub_regions WHERE user_id = v_user_id AND region_id = v_region_id AND name = r.sub_region LIMIT 1;
    IF v_sub_id IS NULL THEN
      INSERT INTO public.wine_sub_regions(user_id,region_id,name,sort_order)
      VALUES (v_user_id, v_region_id, r.sub_region, (SELECT COALESCE(MAX(sort_order),0)+1 FROM public.wine_sub_regions WHERE user_id=v_user_id AND region_id=v_region_id))
      RETURNING id INTO v_sub_id;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.wine_appellations WHERE user_id=v_user_id AND sub_region_id=v_sub_id AND name=r.aname) THEN
      INSERT INTO public.wine_appellations(user_id,sub_region_id,name,appellation_type,sort_order)
      VALUES (v_user_id, v_sub_id, r.aname, r.atype, (SELECT COALESCE(MAX(sort_order),0)+1 FROM public.wine_appellations WHERE user_id=v_user_id AND sub_region_id=v_sub_id));
    END IF;
  END LOOP;
END $$;